/* ============================================================
   ket-db.js — Cambridge A2 Key 核心词库
   范围：精选 380 词，覆盖 A2 Key Vocabulary List 常见主题
   来源：Cambridge A2 Key / A2 Key for Schools Vocabulary List
   ============================================================ */

// 词条结构：word, pos, meaning_zh, topic, difficulty(1=基础 2=普通 3=难拼写), example_en?
// example_en 只对部分词附极简单例句

const KET_WORDS = [
  // ===== Education / School =====
  { word: 'school',  pos: 'n.', zh: '学校', topic: 'Education', difficulty: 1 },
  { word: 'class',   pos: 'n.', zh: '班级；课', topic: 'Education', difficulty: 1 },
  { word: 'teacher', pos: 'n.', zh: '老师', topic: 'Education', difficulty: 1 },
  { word: 'student', pos: 'n.', zh: '学生', topic: 'Education', difficulty: 1 },
  { word: 'lesson',  pos: 'n.', zh: '课；功课', topic: 'Education', difficulty: 2 },
  { word: 'homework',pos: 'n.', zh: '家庭作业', topic: 'Education', difficulty: 2 },
  { word: 'test',    pos: 'n.', zh: '测验', topic: 'Education', difficulty: 1 },
  { word: 'exam',    pos: 'n.', zh: '考试', topic: 'Education', difficulty: 1 },
  { word: 'mark',    pos: 'n.', zh: '分数', topic: 'Education', difficulty: 2 },
  { word: 'grade',   pos: 'n.', zh: '成绩；年级', topic: 'Education', difficulty: 2 },
  { word: 'subject', pos: 'n.', zh: '学科', topic: 'Education', difficulty: 2 },
  { word: 'pen',     pos: 'n.', zh: '钢笔', topic: 'Education', difficulty: 1 },
  { word: 'pencil',  pos: 'n.', zh: '铅笔', topic: 'Education', difficulty: 1 },
  { word: 'ruler',   pos: 'n.', zh: '尺子', topic: 'Education', difficulty: 2 },
  { word: 'book',    pos: 'n.', zh: '书', topic: 'Education', difficulty: 1 },
  { word: 'page',    pos: 'n.', zh: '页', topic: 'Education', difficulty: 1 },
  { word: 'dictionary', pos: 'n.', zh: '字典', topic: 'Education', difficulty: 3, ex: 'Use a dictionary.' },
  { word: 'library', pos: 'n.', zh: '图书馆', topic: 'Education', difficulty: 3, ex: 'She is in the library.' },
  { word: 'university', pos: 'n.', zh: '大学', topic: 'Education', difficulty: 3 },
  { word: 'answer',  pos: 'n./v.', zh: '回答', topic: 'Education', difficulty: 2 },
  { word: 'question', pos: 'n.', zh: '问题', topic: 'Education', difficulty: 2 },
  { word: 'learn',   pos: 'v.', zh: '学习', topic: 'Education', difficulty: 1 },
  { word: 'study',   pos: 'v.', zh: '学习；攻读', topic: 'Education', difficulty: 1 },
  { word: 'teach',   pos: 'v.', zh: '教', topic: 'Education', difficulty: 1 },
  { word: 'read',    pos: 'v.', zh: '读', topic: 'Education', difficulty: 1 },
  { word: 'write',   pos: 'v.', zh: '写', topic: 'Education', difficulty: 1 },
  { word: 'speak',   pos: 'v.', zh: '说', topic: 'Education', difficulty: 2 },
  { word: 'listen',  pos: 'v.', zh: '听', topic: 'Education', difficulty: 2 },
  { word: 'spell',   pos: 'v.', zh: '拼写', topic: 'Education', difficulty: 2 },
  { word: 'remember',pos: 'v.', zh: '记住', topic: 'Education', difficulty: 3 },
  { word: 'understand', pos: 'v.', zh: '理解', topic: 'Education', difficulty: 3 },

  // ===== Family and Friends =====
  { word: 'family',  pos: 'n.', zh: '家庭', topic: 'Family and Friends', difficulty: 1 },
  { word: 'mother',  pos: 'n.', zh: '妈妈', topic: 'Family and Friends', difficulty: 1 },
  { word: 'father',  pos: 'n.', zh: '爸爸', topic: 'Family and Friends', difficulty: 1 },
  { word: 'sister',  pos: 'n.', zh: '姐姐；妹妹', topic: 'Family and Friends', difficulty: 1 },
  { word: 'brother', pos: 'n.', zh: '哥哥；弟弟', topic: 'Family and Friends', difficulty: 1 },
  { word: 'parent',  pos: 'n.', zh: '父母', topic: 'Family and Friends', difficulty: 2 },
  { word: 'baby',    pos: 'n.', zh: '宝宝', topic: 'Family and Friends', difficulty: 1 },
  { word: 'child',   pos: 'n.', zh: '孩子', topic: 'Family and Friends', difficulty: 1 },
  { word: 'friend',  pos: 'n.', zh: '朋友', topic: 'Family and Friends', difficulty: 1 },
  { word: 'boy',     pos: 'n.', zh: '男孩', topic: 'Family and Friends', difficulty: 1 },
  { word: 'girl',    pos: 'n.', zh: '女孩', topic: 'Family and Friends', difficulty: 1 },
  { word: 'man',     pos: 'n.', zh: '男人', topic: 'Family and Friends', difficulty: 1 },
  { word: 'woman',   pos: 'n.', zh: '女人', topic: 'Family and Friends', difficulty: 1 },
  { word: 'people',  pos: 'n.', zh: '人们', topic: 'Family and Friends', difficulty: 1 },
  { word: 'name',    pos: 'n.', zh: '名字', topic: 'Personal Information', difficulty: 1 },
  { word: 'age',     pos: 'n.', zh: '年龄', topic: 'Personal Information', difficulty: 1 },
  { word: 'birthday',pos: 'n.', zh: '生日', topic: 'Personal Information', difficulty: 2 },
  { word: 'uncle',   pos: 'n.', zh: '叔叔；舅舅', topic: 'Family and Friends', difficulty: 2 },
  { word: 'aunt',    pos: 'n.', zh: '阿姨；姑姑', topic: 'Family and Friends', difficulty: 1 },
  { word: 'cousin',  pos: 'n.', zh: '堂（表）兄弟姐妹', topic: 'Family and Friends', difficulty: 3 },
  { word: 'grandmother', pos: 'n.', zh: '祖母；外祖母', topic: 'Family and Friends', difficulty: 3 },
  { word: 'grandfather', pos: 'n.', zh: '祖父；外祖父', topic: 'Family and Friends', difficulty: 3 },
  { word: 'husband', pos: 'n.', zh: '丈夫', topic: 'Family and Friends', difficulty: 2 },
  { word: 'wife',    pos: 'n.', zh: '妻子', topic: 'Family and Friends', difficulty: 1 },
  { word: 'neighbour', pos: 'n.', zh: '邻居', topic: 'Family and Friends', difficulty: 3 },
  { word: 'love',    pos: 'v./n.', zh: '爱', topic: 'Feelings', difficulty: 1 },
  { word: 'miss',    pos: 'v.', zh: '想念', topic: 'Feelings', difficulty: 2 },

  // ===== Food and Drink =====
  { word: 'food',    pos: 'n.', zh: '食物', topic: 'Food and Drink', difficulty: 1 },
  { word: 'water',   pos: 'n.', zh: '水', topic: 'Food and Drink', difficulty: 1 },
  { word: 'milk',    pos: 'n.', zh: '牛奶', topic: 'Food and Drink', difficulty: 1 },
  { word: 'tea',     pos: 'n.', zh: '茶', topic: 'Food and Drink', difficulty: 1 },
  { word: 'coffee',  pos: 'n.', zh: '咖啡', topic: 'Food and Drink', difficulty: 3 },
  { word: 'juice',   pos: 'n.', zh: '果汁', topic: 'Food and Drink', difficulty: 2 },
  { word: 'rice',    pos: 'n.', zh: '米饭', topic: 'Food and Drink', difficulty: 1 },
  { word: 'bread',   pos: 'n.', zh: '面包', topic: 'Food and Drink', difficulty: 1 },
  { word: 'egg',     pos: 'n.', zh: '鸡蛋', topic: 'Food and Drink', difficulty: 1 },
  { word: 'meat',    pos: 'n.', zh: '肉', topic: 'Food and Drink', difficulty: 1 },
  { word: 'fish',    pos: 'n.', zh: '鱼', topic: 'Food and Drink', difficulty: 1 },
  { word: 'chicken', pos: 'n.', zh: '鸡肉', topic: 'Food and Drink', difficulty: 2 },
  { word: 'vegetable', pos: 'n.', zh: '蔬菜', topic: 'Food and Drink', difficulty: 3 },
  { word: 'fruit',   pos: 'n.', zh: '水果', topic: 'Food and Drink', difficulty: 1 },
  { word: 'apple',   pos: 'n.', zh: '苹果', topic: 'Food and Drink', difficulty: 1 },
  { word: 'banana',  pos: 'n.', zh: '香蕉', topic: 'Food and Drink', difficulty: 1 },
  { word: 'orange',  pos: 'n.', zh: '橙子', topic: 'Food and Drink', difficulty: 1 },
  { word: 'cake',    pos: 'n.', zh: '蛋糕', topic: 'Food and Drink', difficulty: 1 },
  { word: 'ice cream', pos: 'n.', zh: '冰淇淋', topic: 'Food and Drink', difficulty: 2 },
  { word: 'sugar',   pos: 'n.', zh: '糖', topic: 'Food and Drink', difficulty: 2 },
  { word: 'salt',    pos: 'n.', zh: '盐', topic: 'Food and Drink', difficulty: 1 },
  { word: 'breakfast', pos: 'n.', zh: '早餐', topic: 'Food and Drink', difficulty: 2 },
  { word: 'lunch',   pos: 'n.', zh: '午餐', topic: 'Food and Drink', difficulty: 1 },
  { word: 'dinner',  pos: 'n.', zh: '晚餐', topic: 'Food and Drink', difficulty: 1 },
  { word: 'meal',    pos: 'n.', zh: '一餐', topic: 'Food and Drink', difficulty: 1 },
  { word: 'hungry',  pos: 'adj.', zh: '饥饿的', topic: 'Food and Drink', difficulty: 2 },
  { word: 'thirsty', pos: 'adj.', zh: '口渴的', topic: 'Food and Drink', difficulty: 2 },
  { word: 'drink',   pos: 'v./n.', zh: '喝；饮料', topic: 'Food and Drink', difficulty: 1 },
  { word: 'eat',     pos: 'v.', zh: '吃', topic: 'Food and Drink', difficulty: 1 },
  { word: 'cook',    pos: 'v.', zh: '做饭', topic: 'Food and Drink', difficulty: 1 },

  // ===== House and Home =====
  { word: 'house',   pos: 'n.', zh: '房子', topic: 'House and Home', difficulty: 1 },
  { word: 'home',    pos: 'n.', zh: '家', topic: 'House and Home', difficulty: 1 },
  { word: 'room',    pos: 'n.', zh: '房间', topic: 'House and Home', difficulty: 1 },
  { word: 'door',    pos: 'n.', zh: '门', topic: 'House and Home', difficulty: 1 },
  { word: 'window',  pos: 'n.', zh: '窗户', topic: 'House and Home', difficulty: 2 },
  { word: 'wall',    pos: 'n.', zh: '墙', topic: 'House and Home', difficulty: 1 },
  { word: 'floor',   pos: 'n.', zh: '地板', topic: 'House and Home', difficulty: 1 },
  { word: 'roof',    pos: 'n.', zh: '屋顶', topic: 'House and Home', difficulty: 1 },
  { word: 'bed',     pos: 'n.', zh: '床', topic: 'House and Home', difficulty: 1 },
  { word: 'table',   pos: 'n.', zh: '桌子', topic: 'House and Home', difficulty: 1 },
  { word: 'chair',   pos: 'n.', zh: '椅子', topic: 'House and Home', difficulty: 1 },
  { word: 'sofa',    pos: 'n.', zh: '沙发', topic: 'House and Home', difficulty: 1 },
  { word: 'lamp',    pos: 'n.', zh: '灯', topic: 'House and Home', difficulty: 1 },
  { word: 'mirror',  pos: 'n.', zh: '镜子', topic: 'House and Home', difficulty: 2 },
  { word: 'kitchen', pos: 'n.', zh: '厨房', topic: 'House and Home', difficulty: 2 },
  { word: 'bathroom',pos: 'n.', zh: '浴室', topic: 'House and Home', difficulty: 2 },
  { word: 'bedroom', pos: 'n.', zh: '卧室', topic: 'House and Home', difficulty: 2 },
  { word: 'garden',  pos: 'n.', zh: '花园', topic: 'House and Home', difficulty: 2 },
  { word: 'garage',  pos: 'n.', zh: '车库', topic: 'House and Home', difficulty: 2 },
  { word: 'key',     pos: 'n.', zh: '钥匙', topic: 'House and Home', difficulty: 1 },
  { word: 'address', pos: 'n.', zh: '地址', topic: 'Personal Information', difficulty: 3 },
  { word: 'live',    pos: 'v.', zh: '住；生活', topic: 'House and Home', difficulty: 1 },
  { word: 'clean',   pos: 'v./adj.', zh: '打扫；干净的', topic: 'Daily Life', difficulty: 1 },

  // ===== Sport =====
  { word: 'sport',   pos: 'n.', zh: '运动', topic: 'Sport', difficulty: 1 },
  { word: 'football', pos: 'n.', zh: '足球', topic: 'Sport', difficulty: 3 },
  { word: 'basketball', pos: 'n.', zh: '篮球', topic: 'Sport', difficulty: 3 },
  { word: 'tennis',  pos: 'n.', zh: '网球', topic: 'Sport', difficulty: 2 },
  { word: 'swim',    pos: 'v.', zh: '游泳', topic: 'Sport', difficulty: 1 },
  { word: 'swimming',pos: 'n.', zh: '游泳', topic: 'Sport', difficulty: 2 },
  { word: 'run',     pos: 'v.', zh: '跑', topic: 'Sport', difficulty: 1 },
  { word: 'jump',    pos: 'v.', zh: '跳', topic: 'Sport', difficulty: 1 },
  { word: 'play',    pos: 'v.', zh: '玩；参加（比赛）', topic: 'Free Time', difficulty: 1 },
  { word: 'win',     pos: 'v.', zh: '赢', topic: 'Sport', difficulty: 1 },
  { word: 'lose',    pos: 'v.', zh: '输；丢失', topic: 'Sport', difficulty: 1 },
  { word: 'team',    pos: 'n.', zh: '队伍', topic: 'Sport', difficulty: 1 },
  { word: 'player',  pos: 'n.', zh: '运动员', topic: 'Sport', difficulty: 2 },
  { word: 'game',    pos: 'n.', zh: '比赛；游戏', topic: 'Free Time', difficulty: 1 },
  { word: 'match',   pos: 'n.', zh: '比赛', topic: 'Sport', difficulty: 2 },
  { word: 'ball',    pos: 'n.', zh: '球', topic: 'Sport', difficulty: 1 },
  { word: 'train',   pos: 'v.', zh: '训练', topic: 'Sport', difficulty: 2 },
  { word: 'ride',    pos: 'v.', zh: '骑', topic: 'Sport', difficulty: 2 },

  // ===== Health =====
  { word: 'health',  pos: 'n.', zh: '健康', topic: 'Health', difficulty: 2 },
  { word: 'doctor',  pos: 'n.', zh: '医生', topic: 'Health', difficulty: 2 },
  { word: 'nurse',   pos: 'n.', zh: '护士', topic: 'Health', difficulty: 1 },
  { word: 'hospital',pos: 'n.', zh: '医院', topic: 'Health', difficulty: 3 },
  { word: 'medicine',pos: 'n.', zh: '药', topic: 'Health', difficulty: 3 },
  { word: 'headache',pos: 'n.', zh: '头痛', topic: 'Health', difficulty: 3 },
  { word: 'fever',   pos: 'n.', zh: '发烧', topic: 'Health', difficulty: 2 },
  { word: 'cold',    pos: 'n./adj.', zh: '感冒；冷的', topic: 'Health', difficulty: 1 },
  { word: 'cough',   pos: 'n./v.', zh: '咳嗽', topic: 'Health', difficulty: 2 },
  { word: 'toothache', pos: 'n.', zh: '牙痛', topic: 'Health', difficulty: 3 },
  { word: 'hurt',    pos: 'v.', zh: '受伤', topic: 'Health', difficulty: 1 },
  { word: 'tired',   pos: 'adj.', zh: '疲倦的', topic: 'Feelings', difficulty: 2 },
  { word: 'better',  pos: 'adj.', zh: '更好的', topic: 'Health', difficulty: 2 },
  { word: 'well',    pos: 'adj.', zh: '健康的；好的', topic: 'Health', difficulty: 1 },
  { word: 'sleep',   pos: 'v./n.', zh: '睡', topic: 'Daily Life', difficulty: 1 },

  // ===== Clothes =====
  { word: 'clothes', pos: 'n.', zh: '衣服', topic: 'Clothes', difficulty: 2 },
  { word: 'shirt',   pos: 'n.', zh: '衬衫', topic: 'Clothes', difficulty: 1 },
  { word: 'T-shirt', pos: 'n.', zh: 'T 恤', topic: 'Clothes', difficulty: 2 },
  { word: 'trousers',pos: 'n.', zh: '裤子', topic: 'Clothes', difficulty: 2 },
  { word: 'jeans',   pos: 'n.', zh: '牛仔裤', topic: 'Clothes', difficulty: 2 },
  { word: 'skirt',   pos: 'n.', zh: '裙子', topic: 'Clothes', difficulty: 1 },
  { word: 'dress',   pos: 'n.', zh: '连衣裙', topic: 'Clothes', difficulty: 1 },
  { word: 'shoe',    pos: 'n.', zh: '鞋', topic: 'Clothes', difficulty: 1 },
  { word: 'socks',   pos: 'n.', zh: '袜子', topic: 'Clothes', difficulty: 1 },
  { word: 'hat',     pos: 'n.', zh: '帽子', topic: 'Clothes', difficulty: 1 },
  { word: 'cap',     pos: 'n.', zh: '棒球帽', topic: 'Clothes', difficulty: 1 },
  { word: 'coat',    pos: 'n.', zh: '外套', topic: 'Clothes', difficulty: 1 },
  { word: 'jacket',  pos: 'n.', zh: '夹克', topic: 'Clothes', difficulty: 2 },
  { word: 'wear',    pos: 'v.', zh: '穿', topic: 'Clothes', difficulty: 1 },
  { word: 'put on',  pos: 'v.', zh: '穿上', topic: 'Clothes', difficulty: 2 },

  // ===== Travel / Transport =====
  { word: 'travel',  pos: 'v./n.', zh: '旅行', topic: 'Travel', difficulty: 2 },
  { word: 'trip',    pos: 'n.', zh: '旅行', topic: 'Travel', difficulty: 1 },
  { word: 'holiday', pos: 'n.', zh: '假期', topic: 'Travel', difficulty: 3 },
  { word: 'hotel',   pos: 'n.', zh: '酒店', topic: 'Travel', difficulty: 2 },
  { word: 'ticket',  pos: 'n.', zh: '票', topic: 'Travel', difficulty: 2 },
  { word: 'passport',pos: 'n.', zh: '护照', topic: 'Travel', difficulty: 3 },
  { word: 'suitcase',pos: 'n.', zh: '行李箱', topic: 'Travel', difficulty: 3 },
  { word: 'beach',   pos: 'n.', zh: '海滩', topic: 'Places', difficulty: 1 },
  { word: 'sea',     pos: 'n.', zh: '海', topic: 'Places', difficulty: 1 },
  { word: 'mountain',pos: 'n.', zh: '山', topic: 'Places', difficulty: 2 },
  { word: 'map',     pos: 'n.', zh: '地图', topic: 'Travel', difficulty: 1 },
  { word: 'tourist', pos: 'n.', zh: '游客', topic: 'Travel', difficulty: 2 },
  { word: 'guide',   pos: 'n.', zh: '向导；指南', topic: 'Travel', difficulty: 1 },
  { word: 'car',     pos: 'n.', zh: '汽车', topic: 'Transport', difficulty: 1 },
  { word: 'bus',     pos: 'n.', zh: '公共汽车', topic: 'Transport', difficulty: 1 },
  { word: 'train',   pos: 'n.', zh: '火车', topic: 'Transport', difficulty: 1 },
  { word: 'plane',   pos: 'n.', zh: '飞机', topic: 'Transport', difficulty: 1 },
  { word: 'taxi',    pos: 'n.', zh: '出租车', topic: 'Transport', difficulty: 2 },
  { word: 'bicycle', pos: 'n.', zh: '自行车', topic: 'Transport', difficulty: 3 },
  { word: 'station', pos: 'n.', zh: '车站', topic: 'Transport', difficulty: 2 },
  { word: 'airport', pos: 'n.', zh: '机场', topic: 'Transport', difficulty: 3 },
  { word: 'road',    pos: 'n.', zh: '路', topic: 'Transport', difficulty: 1 },
  { word: 'street',  pos: 'n.', zh: '街道', topic: 'Places', difficulty: 1 },
  { word: 'bridge',  pos: 'n.', zh: '桥', topic: 'Places', difficulty: 2 },
  { word: 'drive',   pos: 'v.', zh: '驾驶', topic: 'Transport', difficulty: 2 },
  { word: 'walk',    pos: 'v./n.', zh: '走；步行', topic: 'Daily Life', difficulty: 1 },
  { word: 'fly',     pos: 'v.', zh: '飞', topic: 'Transport', difficulty: 1 },

  // ===== Daily Life =====
  { word: 'morning', pos: 'n.', zh: '早晨', topic: 'Time', difficulty: 2 },
  { word: 'afternoon', pos: 'n.', zh: '下午', topic: 'Time', difficulty: 3 },
  { word: 'evening', pos: 'n.', zh: '傍晚', topic: 'Time', difficulty: 2 },
  { word: 'night',   pos: 'n.', zh: '夜晚', topic: 'Time', difficulty: 1 },
  { word: 'day',     pos: 'n.', zh: '一天', topic: 'Time', difficulty: 1 },
  { word: 'week',    pos: 'n.', zh: '周', topic: 'Time', difficulty: 1 },
  { word: 'month',   pos: 'n.', zh: '月', topic: 'Time', difficulty: 1 },
  { word: 'year',    pos: 'n.', zh: '年', topic: 'Time', difficulty: 1 },
  { word: 'today',   pos: 'adv.', zh: '今天', topic: 'Time', difficulty: 1 },
  { word: 'tomorrow',pos: 'adv.', zh: '明天', topic: 'Time', difficulty: 3 },
  { word: 'yesterday', pos: 'adv.', zh: '昨天', topic: 'Time', difficulty: 3 },
  { word: 'time',    pos: 'n.', zh: '时间', topic: 'Time', difficulty: 1 },
  { word: 'hour',    pos: 'n.', zh: '小时', topic: 'Time', difficulty: 1 },
  { word: 'minute',  pos: 'n.', zh: '分钟', topic: 'Time', difficulty: 2 },
  { word: 'o\'clock',pos: 'adv.', zh: '点钟', topic: 'Time', difficulty: 2 },
  { word: 'early',   pos: 'adv.', zh: '早', topic: 'Time', difficulty: 2 },
  { word: 'late',    pos: 'adv.', zh: '晚', topic: 'Time', difficulty: 1 },
  { word: 'always',  pos: 'adv.', zh: '总是', topic: 'Time', difficulty: 3 },
  { word: 'usually', pos: 'adv.', zh: '通常', topic: 'Time', difficulty: 3 },
  { word: 'often',   pos: 'adv.', zh: '经常', topic: 'Time', difficulty: 2 },
  { word: 'sometimes', pos: 'adv.', zh: '有时', topic: 'Time', difficulty: 3 },
  { word: 'never',   pos: 'adv.', zh: '从不', topic: 'Time', difficulty: 2 },
  { word: 'every day', pos: 'adv.', zh: '每天', topic: 'Time', difficulty: 2 },
  { word: 'wash',    pos: 'v.', zh: '洗', topic: 'Daily Life', difficulty: 1 },
  { word: 'wake up', pos: 'v.', zh: '醒来', topic: 'Daily Life', difficulty: 2 },
  { word: 'get up',  pos: 'v.', zh: '起床', topic: 'Daily Life', difficulty: 2 },
  { word: 'brush',   pos: 'v.', zh: '刷', topic: 'Daily Life', difficulty: 1 },
  { word: 'finish',  pos: 'v.', zh: '完成', topic: 'Daily Life', difficulty: 2 },
  { word: 'start',   pos: 'v.', zh: '开始', topic: 'Daily Life', difficulty: 1 },
  { word: 'begin',   pos: 'v.', zh: '开始', topic: 'Daily Life', difficulty: 2 },
  { word: 'stop',    pos: 'v.', zh: '停止', topic: 'Daily Life', difficulty: 1 },
  { word: 'wait',    pos: 'v.', zh: '等待', topic: 'Daily Life', difficulty: 1 },
  { word: 'use',     pos: 'v.', zh: '使用', topic: 'Daily Life', difficulty: 1 },
  { word: 'open',    pos: 'v.', zh: '打开', topic: 'Daily Life', difficulty: 1 },
  { word: 'close',   pos: 'v.', zh: '关闭', topic: 'Daily Life', difficulty: 1 },
  { word: 'work',    pos: 'v./n.', zh: '工作', topic: 'Jobs', difficulty: 1 },
  { word: 'help',    pos: 'v./n.', zh: '帮助', topic: 'Daily Life', difficulty: 1 },
  { word: 'enjoy',   pos: 'v.', zh: '享受', topic: 'Feelings', difficulty: 2 },
  { word: 'try',     pos: 'v.', zh: '尝试', topic: 'Daily Life', difficulty: 1 },
  { word: 'need',    pos: 'v.', zh: '需要', topic: 'Daily Life', difficulty: 1 },
  { word: 'want',    pos: 'v.', zh: '想要', topic: 'Daily Life', difficulty: 1 },
  { word: 'like',    pos: 'v.', zh: '喜欢', topic: 'Feelings', difficulty: 1 },
  { word: 'have',    pos: 'v.', zh: '有', topic: 'Daily Life', difficulty: 1 },
  { word: 'do',      pos: 'v.', zh: '做', topic: 'Daily Life', difficulty: 1 },
  { word: 'go',      pos: 'v.', zh: '去', topic: 'Daily Life', difficulty: 1 },
  { word: 'come',    pos: 'v.', zh: '来', topic: 'Daily Life', difficulty: 1 },
  { word: 'make',    pos: 'v.', zh: '制作', topic: 'Daily Life', difficulty: 1 },
  { word: 'take',    pos: 'v.', zh: '拿；花费', topic: 'Daily Life', difficulty: 1 },
  { word: 'give',    pos: 'v.', zh: '给', topic: 'Daily Life', difficulty: 1 },
  { word: 'get',     pos: 'v.', zh: '得到；到达', topic: 'Daily Life', difficulty: 1 },
  { word: 'put',     pos: 'v.', zh: '放', topic: 'Daily Life', difficulty: 1 },
  { word: 'find',    pos: 'v.', zh: '找到', topic: 'Daily Life', difficulty: 1 },
  { word: 'buy',     pos: 'v.', zh: '买', topic: 'Shopping', difficulty: 1 },
  { word: 'sell',    pos: 'v.', zh: '卖', topic: 'Shopping', difficulty: 1 },
  { word: 'pay',     pos: 'v.', zh: '付钱', topic: 'Shopping', difficulty: 1 },
  { word: 'cost',    pos: 'v.', zh: '花费', topic: 'Shopping', difficulty: 1 },
  { word: 'carry',   pos: 'v.', zh: '携带', topic: 'Daily Life', difficulty: 2 },

  // ===== Free Time / Entertainment =====
  { word: 'music',   pos: 'n.', zh: '音乐', topic: 'Free Time', difficulty: 1 },
  { word: 'song',    pos: 'n.', zh: '歌', topic: 'Free Time', difficulty: 1 },
  { word: 'sing',    pos: 'v.', zh: '唱', topic: 'Free Time', difficulty: 1 },
  { word: 'dance',   pos: 'v./n.', zh: '跳舞', topic: 'Free Time', difficulty: 1 },
  { word: 'film',    pos: 'n.', zh: '电影', topic: 'Entertainment', difficulty: 1 },
  { word: 'movie',   pos: 'n.', zh: '电影', topic: 'Entertainment', difficulty: 2 },
  { word: 'cinema',  pos: 'n.', zh: '电影院', topic: 'Entertainment', difficulty: 3 },
  { word: 'TV',      pos: 'n.', zh: '电视', topic: 'Entertainment', difficulty: 1 },
  { word: 'show',    pos: 'n.', zh: '节目', topic: 'Entertainment', difficulty: 1 },
  { word: 'picture', pos: 'n.', zh: '图画', topic: 'Entertainment', difficulty: 2 },
  { word: 'photo',   pos: 'n.', zh: '照片', topic: 'Entertainment', difficulty: 2 },
  { word: 'camera',  pos: 'n.', zh: '相机', topic: 'Technology', difficulty: 3 },
  { word: 'book',    pos: 'n.', zh: '书', topic: 'Free Time', difficulty: 1 },
  { word: 'story',   pos: 'n.', zh: '故事', topic: 'Entertainment', difficulty: 2 },
  { word: 'paint',   pos: 'v.', zh: '画', topic: 'Free Time', difficulty: 1 },
  { word: 'draw',    pos: 'v.', zh: '画', topic: 'Free Time', difficulty: 1 },
  { word: 'hobby',   pos: 'n.', zh: '爱好', topic: 'Free Time', difficulty: 2 },
  { word: 'fun',     pos: 'n./adj.', zh: '乐趣', topic: 'Free Time', difficulty: 1 },
  { word: 'party',   pos: 'n.', zh: '聚会', topic: 'Free Time', difficulty: 2 },
  { word: 'favourite', pos: 'adj.', zh: '最喜爱的', topic: 'Feelings', difficulty: 3 },
  { word: 'free',    pos: 'adj.', zh: '空闲的', topic: 'Free Time', difficulty: 1 },

  // ===== Technology =====
  { word: 'computer',pos: 'n.', zh: '电脑', topic: 'Technology', difficulty: 3 },
  { word: 'phone',   pos: 'n.', zh: '电话', topic: 'Technology', difficulty: 1 },
  { word: 'mobile',  pos: 'adj./n.', zh: '手机的；手机', topic: 'Technology', difficulty: 2 },
  { word: 'screen',  pos: 'n.', zh: '屏幕', topic: 'Technology', difficulty: 2 },
  { word: 'keyboard',pos: 'n.', zh: '键盘', topic: 'Technology', difficulty: 3 },
  { word: 'email',   pos: 'n./v.', zh: '邮件', topic: 'Communication', difficulty: 2 },
  { word: 'message', pos: 'n.', zh: '信息', topic: 'Communication', difficulty: 2 },
  { word: 'website', pos: 'n.', zh: '网站', topic: 'Technology', difficulty: 3 },
  { word: 'video',   pos: 'n.', zh: '视频', topic: 'Technology', difficulty: 2 },
  { word: 'app',     pos: 'n.', zh: '应用', topic: 'Technology', difficulty: 1 },
  { word: 'download',pos: 'v.', zh: '下载', topic: 'Technology', difficulty: 3 },
  { word: 'battery', pos: 'n.', zh: '电池', topic: 'Technology', difficulty: 3 },
  { word: 'charge',  pos: 'v.', zh: '充电', topic: 'Technology', difficulty: 2 },

  // ===== Weather =====
  { word: 'weather', pos: 'n.', zh: '天气', topic: 'Weather', difficulty: 2 },
  { word: 'sun',     pos: 'n.', zh: '太阳', topic: 'Weather', difficulty: 1 },
  { word: 'sunny',   pos: 'adj.', zh: '晴朗的', topic: 'Weather', difficulty: 2 },
  { word: 'rain',    pos: 'n./v.', zh: '雨；下雨', topic: 'Weather', difficulty: 1 },
  { word: 'rainy',   pos: 'adj.', zh: '下雨的', topic: 'Weather', difficulty: 2 },
  { word: 'cloud',   pos: 'n.', zh: '云', topic: 'Weather', difficulty: 1 },
  { word: 'cloudy',  pos: 'adj.', zh: '多云的', topic: 'Weather', difficulty: 2 },
  { word: 'wind',    pos: 'n.', zh: '风', topic: 'Weather', difficulty: 1 },
  { word: 'windy',   pos: 'adj.', zh: '有风的', topic: 'Weather', difficulty: 2 },
  { word: 'snow',    pos: 'n./v.', zh: '雪；下雪', topic: 'Weather', difficulty: 1 },
  { word: 'hot',     pos: 'adj.', zh: '热的', topic: 'Weather', difficulty: 1 },
  { word: 'warm',    pos: 'adj.', zh: '温暖的', topic: 'Weather', difficulty: 1 },
  { word: 'cool',    pos: 'adj.', zh: '凉爽的', topic: 'Weather', difficulty: 1 },
  { word: 'cold',    pos: 'adj.', zh: '冷的', topic: 'Weather', difficulty: 1 },

  // ===== Places =====
  { word: 'city',    pos: 'n.', zh: '城市', topic: 'Places', difficulty: 1 },
  { word: 'town',    pos: 'n.', zh: '镇', topic: 'Places', difficulty: 1 },
  { word: 'country', pos: 'n.', zh: '国家', topic: 'Places', difficulty: 2 },
  { word: 'village', pos: 'n.', zh: '村庄', topic: 'Places', difficulty: 3 },
  { word: 'park',    pos: 'n.', zh: '公园', topic: 'Places', difficulty: 1 },
  { word: 'shop',    pos: 'n.', zh: '商店', topic: 'Shopping', difficulty: 1 },
  { word: 'store',   pos: 'n.', zh: '商店', topic: 'Shopping', difficulty: 1 },
  { word: 'supermarket', pos: 'n.', zh: '超市', topic: 'Shopping', difficulty: 3 },
  { word: 'market',  pos: 'n.', zh: '市场', topic: 'Shopping', difficulty: 2 },
  { word: 'bank',    pos: 'n.', zh: '银行', topic: 'Places', difficulty: 1 },
  { word: 'church',  pos: 'n.', zh: '教堂', topic: 'Places', difficulty: 2 },
  { word: 'museum',  pos: 'n.', zh: '博物馆', topic: 'Places', difficulty: 2 },
  { word: 'restaurant', pos: 'n.', zh: '餐厅', topic: 'Food and Drink', difficulty: 3 },
  { word: 'cafe',    pos: 'n.', zh: '咖啡馆', topic: 'Food and Drink', difficulty: 2 },
  { word: 'pool',    pos: 'n.', zh: '游泳池', topic: 'Places', difficulty: 1 },
  { word: 'river',   pos: 'n.', zh: '河', topic: 'Places', difficulty: 2 },
  { word: 'lake',    pos: 'n.', zh: '湖', topic: 'Places', difficulty: 1 },
  { word: 'forest',  pos: 'n.', zh: '森林', topic: 'Nature', difficulty: 2 },
  { word: 'island',  pos: 'n.', zh: '岛', topic: 'Places', difficulty: 2 },
  { word: 'centre',  pos: 'n.', zh: '中心', topic: 'Places', difficulty: 2 },

  // ===== Shopping =====
  { word: 'money',   pos: 'n.', zh: '钱', topic: 'Shopping', difficulty: 1 },
  { word: 'price',   pos: 'n.', zh: '价格', topic: 'Shopping', difficulty: 2 },
  { word: 'cheap',   pos: 'adj.', zh: '便宜的', topic: 'Shopping', difficulty: 1 },
  { word: 'expensive',pos: 'adj.', zh: '昂贵的', topic: 'Shopping', difficulty: 3 },
  { word: 'sale',    pos: 'n.', zh: '减价销售', topic: 'Shopping', difficulty: 1 },
  { word: 'customer',pos: 'n.', zh: '顾客', topic: 'Shopping', difficulty: 3 },
  { word: 'change',  pos: 'n./v.', zh: '零钱；改变', topic: 'Shopping', difficulty: 2 },
  { word: 'pocket',  pos: 'n.', zh: '口袋', topic: 'Clothes', difficulty: 2 },
  { word: 'bag',     pos: 'n.', zh: '包', topic: 'Shopping', difficulty: 1 },
  { word: 'list',    pos: 'n.', zh: '清单', topic: 'Daily Life', difficulty: 1 },

  // ===== Jobs =====
  { word: 'job',     pos: 'n.', zh: '工作', topic: 'Jobs', difficulty: 1 },
  { word: 'worker',  pos: 'n.', zh: '工人', topic: 'Jobs', difficulty: 2 },
  { word: 'driver',  pos: 'n.', zh: '司机', topic: 'Jobs', difficulty: 2 },
  { word: 'farmer',  pos: 'n.', zh: '农民', topic: 'Jobs', difficulty: 2 },
  { word: 'cook',    pos: 'n.', zh: '厨师', topic: 'Jobs', difficulty: 1 },
  { word: 'artist',  pos: 'n.', zh: '艺术家', topic: 'Jobs', difficulty: 2 },
  { word: 'singer',  pos: 'n.', zh: '歌手', topic: 'Jobs', difficulty: 2 },
  { word: 'writer',  pos: 'n.', zh: '作家', topic: 'Jobs', difficulty: 2 },
  { word: 'manager', pos: 'n.', zh: '经理', topic: 'Jobs', difficulty: 3 },
  { word: 'business',pos: 'n.', zh: '生意', topic: 'Jobs', difficulty: 3 },
  { word: 'company', pos: 'n.', zh: '公司', topic: 'Jobs', difficulty: 3 },
  { word: 'office',  pos: 'n.', zh: '办公室', topic: 'Jobs', difficulty: 2 },
  { word: 'factory', pos: 'n.', zh: '工厂', topic: 'Jobs', difficulty: 3 },
  { word: 'police',  pos: 'n.', zh: '警察', topic: 'Jobs', difficulty: 2 },
  { word: 'uniform', pos: 'n.', zh: '制服', topic: 'Jobs', difficulty: 3 },

  // ===== Communication =====
  { word: 'say',     pos: 'v.', zh: '说', topic: 'Communication', difficulty: 1 },
  { word: 'tell',    pos: 'v.', zh: '告诉', topic: 'Communication', difficulty: 1 },
  { word: 'talk',    pos: 'v.', zh: '谈话', topic: 'Communication', difficulty: 1 },
  { word: 'ask',     pos: 'v.', zh: '问', topic: 'Communication', difficulty: 1 },
  { word: 'answer',  pos: 'v.', zh: '回答', topic: 'Communication', difficulty: 2 },
  { word: 'call',    pos: 'v./n.', zh: '打电话；电话', topic: 'Communication', difficulty: 1 },
  { word: 'shout',   pos: 'v.', zh: '喊', topic: 'Communication', difficulty: 2 },
  { word: 'laugh',   pos: 'v.', zh: '笑', topic: 'Communication', difficulty: 1 },
  { word: 'smile',   pos: 'v./n.', zh: '微笑', topic: 'Communication', difficulty: 2 },
  { word: 'cry',     pos: 'v.', zh: '哭', topic: 'Communication', difficulty: 1 },
  { word: 'letter',  pos: 'n.', zh: '信', topic: 'Communication', difficulty: 2 },
  { word: 'word',    pos: 'n.', zh: '单词', topic: 'Communication', difficulty: 1 },
  { word: 'language',pos: 'n.', zh: '语言', topic: 'Communication', difficulty: 3 },
  { word: 'sentence',pos: 'n.', zh: '句子', topic: 'Education', difficulty: 3 },

  // ===== Feelings =====
  { word: 'happy',   pos: 'adj.', zh: '开心的', topic: 'Feelings', difficulty: 1 },
  { word: 'sad',     pos: 'adj.', zh: '难过的', topic: 'Feelings', difficulty: 1 },
  { word: 'angry',   pos: 'adj.', zh: '生气的', topic: 'Feelings', difficulty: 2 },
  { word: 'afraid',  pos: 'adj.', zh: '害怕的', topic: 'Feelings', difficulty: 2 },
  { word: 'surprised', pos: 'adj.', zh: '惊讶的', topic: 'Feelings', difficulty: 3 },
  { word: 'bored',   pos: 'adj.', zh: '无聊的', topic: 'Feelings', difficulty: 2 },
  { word: 'excited', pos: 'adj.', zh: '兴奋的', topic: 'Feelings', difficulty: 3 },
  { word: 'worried', pos: 'adj.', zh: '担心的', topic: 'Feelings', difficulty: 3 },
  { word: 'kind',    pos: 'adj.', zh: '友好的', topic: 'Feelings', difficulty: 1 },
  { word: 'nice',    pos: 'adj.', zh: '好的', topic: 'Feelings', difficulty: 1 },
  { word: 'great',   pos: 'adj.', zh: '很棒的', topic: 'Feelings', difficulty: 1 },
  { word: 'good',    pos: 'adj.', zh: '好的', topic: 'Feelings', difficulty: 1 },
  { word: 'bad',     pos: 'adj.', zh: '糟糕的', topic: 'Feelings', difficulty: 1 },
  { word: 'new',     pos: 'adj.', zh: '新的', topic: 'Daily Life', difficulty: 1 },
  { word: 'old',     pos: 'adj.', zh: '旧的；老的', topic: 'Daily Life', difficulty: 1 },
  { word: 'big',     pos: 'adj.', zh: '大的', topic: 'Daily Life', difficulty: 1 },
  { word: 'small',   pos: 'adj.', zh: '小的', topic: 'Daily Life', difficulty: 1 },
  { word: 'long',    pos: 'adj.', zh: '长的', topic: 'Daily Life', difficulty: 1 },
  { word: 'short',   pos: 'adj.', zh: '短的；矮的', topic: 'Daily Life', difficulty: 1 },
  { word: 'high',    pos: 'adj.', zh: '高的', topic: 'Daily Life', difficulty: 1 },
  { word: 'tall',    pos: 'adj.', zh: '高的', topic: 'Daily Life', difficulty: 1 },
  { word: 'easy',    pos: 'adj.', zh: '容易的', topic: 'Daily Life', difficulty: 1 },
  { word: 'difficult', pos: 'adj.', zh: '困难的', topic: 'Daily Life', difficulty: 3 },
  { word: 'important', pos: 'adj.', zh: '重要的', topic: 'Daily Life', difficulty: 3 },
  { word: 'right',   pos: 'adj.', zh: '正确的；右边的', topic: 'Daily Life', difficulty: 1 },
  { word: 'wrong',   pos: 'adj.', zh: '错误的', topic: 'Daily Life', difficulty: 1 },
  { word: 'different', pos: 'adj.', zh: '不同的', topic: 'Daily Life', difficulty: 3 },
  { word: 'same',    pos: 'adj.', zh: '相同的', topic: 'Daily Life', difficulty: 1 },
  { word: 'ready',   pos: 'adj.', zh: '准备好的', topic: 'Daily Life', difficulty: 2 },
  { word: 'beautiful', pos: 'adj.', zh: '美丽的', topic: 'Feelings', difficulty: 3 },
  { word: 'because', pos: 'conj.', zh: '因为', topic: 'Daily Life', difficulty: 3 },
  { word: 'but',     pos: 'conj.', zh: '但是', topic: 'Daily Life', difficulty: 1 },
  { word: 'and',     pos: 'conj.', zh: '和', topic: 'Daily Life', difficulty: 1 },
  { word: 'or',      pos: 'conj.', zh: '或者', topic: 'Daily Life', difficulty: 1 },
  { word: 'so',      pos: 'conj.', zh: '所以', topic: 'Daily Life', difficulty: 1 },
  { word: 'with',    pos: 'prep.', zh: '和…一起', topic: 'Daily Life', difficulty: 1 },
  { word: 'without', pos: 'prep.', zh: '没有', topic: 'Daily Life', difficulty: 3 },
  { word: 'in',      pos: 'prep.', zh: '在…里', topic: 'Daily Life', difficulty: 1 },
  { word: 'on',      pos: 'prep.', zh: '在…上', topic: 'Daily Life', difficulty: 1 },
  { word: 'at',      pos: 'prep.', zh: '在…', topic: 'Daily Life', difficulty: 1 },
  { word: 'under',   pos: 'prep.', zh: '在…下', topic: 'Daily Life', difficulty: 2 },
  { word: 'next to', pos: 'prep.', zh: '在旁边', topic: 'Daily Life', difficulty: 2 },
  { word: 'between', pos: 'prep.', zh: '在…之间', topic: 'Daily Life', difficulty: 3 },
  { word: 'before',  pos: 'prep.', zh: '在…之前', topic: 'Time', difficulty: 2 },
  { word: 'after',   pos: 'prep.', zh: '在…之后', topic: 'Time', difficulty: 2 },
  { word: 'during',  pos: 'prep.', zh: '在…期间', topic: 'Time', difficulty: 3 },
  { word: 'around',  pos: 'prep.', zh: '在…周围', topic: 'Daily Life', difficulty: 2 },

  // ===== Animals =====
  { word: 'animal',  pos: 'n.', zh: '动物', topic: 'Animals', difficulty: 2 },
  { word: 'dog',     pos: 'n.', zh: '狗', topic: 'Animals', difficulty: 1 },
  { word: 'cat',     pos: 'n.', zh: '猫', topic: 'Animals', difficulty: 1 },
  { word: 'bird',    pos: 'n.', zh: '鸟', topic: 'Animals', difficulty: 1 },
  { word: 'fish',    pos: 'n.', zh: '鱼', topic: 'Animals', difficulty: 1 },
  { word: 'horse',   pos: 'n.', zh: '马', topic: 'Animals', difficulty: 1 },
  { word: 'rabbit',  pos: 'n.', zh: '兔子', topic: 'Animals', difficulty: 2 },
  { word: 'mouse',   pos: 'n.', zh: '老鼠', topic: 'Animals', difficulty: 1 },
  { word: 'tiger',   pos: 'n.', zh: '老虎', topic: 'Animals', difficulty: 2 },
  { word: 'lion',    pos: 'n.', zh: '狮子', topic: 'Animals', difficulty: 1 },
  { word: 'elephant',pos: 'n.', zh: '大象', topic: 'Animals', difficulty: 3 },
  { word: 'monkey',  pos: 'n.', zh: '猴子', topic: 'Animals', difficulty: 2 },
  { word: 'bear',    pos: 'n.', zh: '熊', topic: 'Animals', difficulty: 1 },
  { word: 'duck',    pos: 'n.', zh: '鸭子', topic: 'Animals', difficulty: 1 },
  { word: 'chicken', pos: 'n.', zh: '鸡', topic: 'Animals', difficulty: 2 },
  { word: 'sheep',   pos: 'n.', zh: '羊', topic: 'Animals', difficulty: 1 },
  { word: 'cow',     pos: 'n.', zh: '奶牛', topic: 'Animals', difficulty: 1 },

  // ===== Nature =====
  { word: 'tree',    pos: 'n.', zh: '树', topic: 'Nature', difficulty: 1 },
  { word: 'flower',  pos: 'n.', zh: '花', topic: 'Nature', difficulty: 2 },
  { word: 'grass',   pos: 'n.', zh: '草', topic: 'Nature', difficulty: 1 },
  { word: 'plant',   pos: 'n.', zh: '植物', topic: 'Nature', difficulty: 1 },
  { word: 'leaf',    pos: 'n.', zh: '叶子', topic: 'Nature', difficulty: 1 },
  { word: 'water',   pos: 'n.', zh: '水', topic: 'Nature', difficulty: 1 },
  { word: 'fire',    pos: 'n.', zh: '火', topic: 'Nature', difficulty: 1 },
  { word: 'air',     pos: 'n.', zh: '空气', topic: 'Nature', difficulty: 1 },
  { word: 'sky',     pos: 'n.', zh: '天空', topic: 'Nature', difficulty: 1 },
  { word: 'star',    pos: 'n.', zh: '星星', topic: 'Nature', difficulty: 1 },
  { word: 'moon',    pos: 'n.', zh: '月亮', topic: 'Nature', difficulty: 1 },
  { word: 'world',   pos: 'n.', zh: '世界', topic: 'Nature', difficulty: 1 },

  // ===== Numbers =====
  { word: 'one',     pos: 'num.', zh: '一', topic: 'Numbers', difficulty: 1 },
  { word: 'two',     pos: 'num.', zh: '二', topic: 'Numbers', difficulty: 1 },
  { word: 'three',   pos: 'num.', zh: '三', topic: 'Numbers', difficulty: 1 },
  { word: 'four',    pos: 'num.', zh: '四', topic: 'Numbers', difficulty: 1 },
  { word: 'five',    pos: 'num.', zh: '五', topic: 'Numbers', difficulty: 1 },
  { word: 'six',     pos: 'num.', zh: '六', topic: 'Numbers', difficulty: 1 },
  { word: 'seven',   pos: 'num.', zh: '七', topic: 'Numbers', difficulty: 2 },
  { word: 'eight',   pos: 'num.', zh: '八', topic: 'Numbers', difficulty: 2 },
  { word: 'nine',    pos: 'num.', zh: '九', topic: 'Numbers', difficulty: 1 },
  { word: 'ten',     pos: 'num.', zh: '十', topic: 'Numbers', difficulty: 1 },
  { word: 'hundred', pos: 'num.', zh: '百', topic: 'Numbers', difficulty: 2 },
  { word: 'thousand',pos: 'num.', zh: '千', topic: 'Numbers', difficulty: 3 },
  { word: 'million', pos: 'num.', zh: '百万', topic: 'Numbers', difficulty: 3 },
  { word: 'first',   pos: 'ord.', zh: '第一', topic: 'Numbers', difficulty: 1 },
  { word: 'second',  pos: 'ord.', zh: '第二', topic: 'Numbers', difficulty: 2 },
  { word: 'next',    pos: 'adj.', zh: '下一个', topic: 'Daily Life', difficulty: 1 },
  { word: 'last',    pos: 'adj.', zh: '最后的', topic: 'Daily Life', difficulty: 1 },

  // ===== Colours =====
  { word: 'red',     pos: 'n./adj.', zh: '红色', topic: 'Colours', difficulty: 1 },
  { word: 'blue',    pos: 'n./adj.', zh: '蓝色', topic: 'Colours', difficulty: 1 },
  { word: 'green',   pos: 'n./adj.', zh: '绿色', topic: 'Colours', difficulty: 1 },
  { word: 'yellow',  pos: 'n./adj.', zh: '黄色', topic: 'Colours', difficulty: 2 },
  { word: 'black',   pos: 'n./adj.', zh: '黑色', topic: 'Colours', difficulty: 1 },
  { word: 'white',   pos: 'n./adj.', zh: '白色', topic: 'Colours', difficulty: 1 },
  { word: 'brown',   pos: 'n./adj.', zh: '棕色', topic: 'Colours', difficulty: 1 },
  { word: 'grey',    pos: 'n./adj.', zh: '灰色', topic: 'Colours', difficulty: 1 },
  { word: 'pink',    pos: 'n./adj.', zh: '粉色', topic: 'Colours', difficulty: 1 },
  { word: 'orange',  pos: 'n./adj.', zh: '橙色', topic: 'Colours', difficulty: 2 },
  { word: 'colour',  pos: 'n.', zh: '颜色', topic: 'Colours', difficulty: 2 },
  { word: 'light',   pos: 'n./adj.', zh: '光；浅色的', topic: 'Daily Life', difficulty: 1 },

  // ===== Documents =====
  { word: 'paper',   pos: 'n.', zh: '纸', topic: 'Documents', difficulty: 1 },
  { word: 'card',    pos: 'n.', zh: '卡片', topic: 'Documents', difficulty: 1 },
  { word: 'form',    pos: 'n.', zh: '表格', topic: 'Documents', difficulty: 1 },
  { word: 'report',  pos: 'n.', zh: '报告', topic: 'Documents', difficulty: 2 },
  { word: 'note',    pos: 'n.', zh: '笔记', topic: 'Documents', difficulty: 1 },
  { word: 'print',   pos: 'v.', zh: '打印', topic: 'Documents', difficulty: 1 },
  { word: 'pen',     pos: 'n.', zh: '钢笔', topic: 'Documents', difficulty: 1 },

  // ===== Personal Information =====
  { word: 'email',   pos: 'n.', zh: '电子邮箱', topic: 'Personal Information', difficulty: 2 },
  { word: 'phone',   pos: 'n.', zh: '电话', topic: 'Personal Information', difficulty: 1 },
  { word: 'number',  pos: 'n.', zh: '号码', topic: 'Numbers', difficulty: 1 },
  { word: 'from',    pos: 'prep.', zh: '来自', topic: 'Personal Information', difficulty: 1 },
  { word: 'nationality', pos: 'n.', zh: '国籍', topic: 'Personal Information', difficulty: 3 },
  { word: 'student', pos: 'n.', zh: '学生', topic: 'Personal Information', difficulty: 1 },
  { word: 'surname', pos: 'n.', zh: '姓', topic: 'Personal Information', difficulty: 2 },
  { word: 'middle',  pos: 'adj.', zh: '中间的', topic: 'Personal Information', difficulty: 2 },
];

// 导出
export function getKETWords() {
  return KET_WORDS;
}

export function buildKETDatabase() {
  // 为每条记录添加 id，从 1 开始
  return KET_WORDS.map((w, i) => ({ id: i + 1, ...w }));
}

export const KET_TOPICS = [
  'Education', 'Family and Friends', 'Food and Drink', 'House and Home',
  'Sport', 'Health', 'Clothes', 'Travel', 'Transport', 'School',
  'Daily Life', 'Free Time', 'Entertainment', 'Technology', 'Weather',
  'Places', 'Shopping', 'Jobs', 'Communication', 'Feelings',
  'Animals', 'Nature', 'Time', 'Numbers', 'Colours', 'Documents',
  'Personal Information',
];
